### ISSUE TITLE
Vocabulary Roadmap 2022.Q4-2023.Q1 (work in progress)

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/vocabulary#1081]
__Notice:__ As there is still much to discover, this Roadmap is considered a `work in progress` and is still subject to change.

## TOC 

* [Summary](#summary)
* [History](#history)
* [Current Challenges](#current-challenges)
* [Objectives](#objectives)

## Summary <a id="summary"></a> 

Vocabulary has become sprawling, out of date, difficult to maintain, mismatched in documentation, and overly complex. It needs to be reconsidered from multiple angles, and given clarity not just in structure, but also approach.

### Goals

1. To reasonably reduce the number of repositories in order to remove unnecessary complexity, and increase maintainability of Vocabulary itself.
2. To solidify a stable enough "foundation" for work to continue with Vocabulary.
3. To update and create consistency among projects where some variation of Vocabulary is a dependency.

#### Code

- `creativecommons/vocabulary` o--o `@creativecommons/vocabulary`					
- `creativecommons/vocabulary-vue` o--o `@creativecommons/vocabulary-vue`

#### Project Structure / Mechanics as a Design System
	
	- Vocabulary 
		- Design Library (Figma), the first order ref point for all design concepts in Vocabulary
			- Tokens
			- Typography
			- Contexts (behavioral, structural)
			- Components (General non-fw specific components)
		- Fonts (Typefaces), which provides typefaces for use in the system
		- Icons (SVGs), which provides a spritekit for use in the system

		- Native Code implementation, the __source of truth__ for all designs in Vocabulary
			- HTML markup for Contexts and Components, which provides base markup for all components/pages
			- CSS library and assets, which provides base CSS styles for all components.
			- JS library and helpers, which provides a helpful base for all components.
	
	- Vue Vocabulary (Vue.js library), 
		- which provides Vue components __derived from__ Vocabulary

#### Why?

Most of the issues with Vocabulary sit within two categories:

1. Original scope misaligned with current scope
2. The Consequences of time

The intended original scale and scope of Vocabulary has shifted dramatically since its original creation, creating conflicting objectives and philosophies.

In many current situations code implementations don't necessarily need a node package to implement Vocabulary, they just need a link to a relevant `vocabulary.css` file hosted on a CDN, and a reference spec for how markup should be output and what adjacent behaviors it should follow. 

More complex setups just need a straight-forward Vue Components library that has Vocabulary itself as a dependency.

From a repository standpoint, Vocabulary started as separate repositories, then became a monorepo, and then back to separate repositories in some instances--and the original monorepo in others. 

This project seeks to move the core of Vocabulary back to a singular repository, and keep the Vocabulary Vue Components implementation as its own repository. There is insufficient documentation for why Vocabulary was split in precisely the ways it was originally, but some of its difficulty in being maintained either as separate repositories or as a monorepo is in how the project is structured overall. The newly proposed structure seeks to address these issues.   

The [Current Challenges](#current-challenges) section does a good job of elaborating further.

### Original Vocabulary
- `creativecommons/vocabulary` o--o `@creativecommons/vocabulary`							
- `creativecommons/fonts` o--o `@creativecommons/fonts`						
- `creativecommons/vue-vocabulary` o--o `@creativecommons/vue-vocabulary`

#### additionally a repository of common CC Assets was created 2020.02.20 to publish to npm
- `creativecommons/cc-assets` o--o `@creativecommons/cc-assets`		 

#### repo migrations
- `creativecommons/vocabulary` --> `creativecommons/vocabulary`			
- `creativecommons/fonts` --> `cc-archive/fonts`
- `creativecommons/vue-vocabulary` --> `cc-archive/vue-vocabulary`	

#### resulting in a monorepo that published three separate packages to npm using lerna.js

- `creativecommons/vocabulary`
	- `/packages/fonts` o--o `@creativecommons/fonts`				
	- `/packages/vocabulary` o--o `@creativecommons/vocabulary`				
	- `/packages/vue-vocabulary` o--o `@creativecommons/vue-vocabulary`

#### cc-assets continued to be used

- `creativecommons/cc-assets` o--o `@creativecommons/cc-assets`	

##### relevant links

- #612

#### repo migrations

- `creativecommons/vocabulary` --> [suspended]
	- `/packages/fonts` --> `creativecommons/vocabulary-fonts`
	- `/packages/vocabulary` --> `creativecommons/vocabulary-styles`
	- `/packages/vue-vocabulary` --> `creativecommons/vocabulary-components`

##### some repository implementations ended up using
- `creativecommons/cc-assets` o--o `@creativecommons/cc-assets`	
- `creativecommons/vocabulary-components` o--o `@creativecommons/vocabulary-components`			
- `creativecommons/vocabulary-fonts` o--o `@creativecommons/vocabulary-fonts`					
- `creativecommons/vocabulary-styles` o--o `@creativecommons/vocabulary-styles`

##### while others continued to use the older packages from
- `creativecommons/vocabulary`
	- `/packages/fonts` o--o `@creativecommons/fonts`
	- `/packages/vocabulary` o--o `@creativecommons/vocabulary`
	- `/packages/vue-vocabulary` o--o `@creativecommons/vue-vocabulary`

##### resulting in the following outcome

- `creativecommons/cc-assets` o--o `@creativecommons/cc-assets`	
- `creativecommons/vocabulary`
	- `/packages/fonts` o--o `@creativecommons/fonts`
	- `/packages/vocabulary` o--o `@creativecommons/vocabulary`
	- `/packages/vue-vocabulary` o--o `@creativecommons/vue-vocabulary`
- `creativecommons/vocabulary-components` o--o `@creativecommons/vocabulary-components`			
- `creativecommons/vocabulary-fonts` o--o `@creativecommons/vocabulary-fonts`					
- `creativecommons/vocabulary-styles` o--o `@creativecommons/vocabulary-styles`

##### relevant links

- #1049	

## Current challenges <a id="current-challenges"></a> 

* Code Rot / Sprawl / Complexity / Performance
* Change in Objective / Scope
* Incomplete Documentation

### Code Rot / Sprawl / Complexity / Performance

- As codebases are utilizing two entirely different implementations of Vocabulary, and the original Vocabulary monorepo is suspended many use cases of Vocabulary are very out of date.
- There's cruft left over in various repositories from the split/mergers that have occurred reducing clarity.
- Many of the CD workflows are broken or possibly not needed. (further investigation needed)
- The use of icons as a font is not a sound Accessible approach, and should largely be replaced with some form of SVG implementation
- `fonts` exist as a package of their own, when there is zero known use for them to be implemented without vocabulary itself.
- the `vocabulary styles` follow the same practice as `fonts`. (In some cases `vocabulary-styles` _was_ the original `vocabulary` repo).
- unpkg has latency issues, especially if a specific version of a file is not required.
- the use of `bulma.js` adds a further layer of abstraction that doesn't actually normalize, but instead resets the default behavior of elements.
	- #1037
	- [bulmajs][bulma_js]
- `storybook` is useful, but also complex. It needs to be reproached with more clarity, or replaced.
	- #630
	- #905

[bulma_js]: https://bulma.io/

#### Node (NPM) as a CDN Pipeline to unpkg

Originally, Vocabulary was built as a robust design system to be used from an application-centric focus. This meant that there were certain challenges when implementing it within setups such as WordPress, since the main core focus was from compatibility with the Node System, and more specifically with Vue.js.

Since then, the focus of Vocabulary use-cases are much more WordPress / Static site centric, with app uses as the secondary priority.

In this way, currently, NPM's major function, and by proxy these repositories existing as Node packages, is to publish them easily to a CDN (unpkg), not to necessarily be consumed as as dependency in Node projects. Individual files (primarily the font and css files) are then often used as `<link>` includes in relevant codebases.

This isn't entirely untenable, but there are likely alternative CDN solutions for this use-case that don't primarily rely on the NPM ecosystem or on unpkg.

#### Source of truth and conflicting design system mechanics 

From the [Storybook documentation](https://cc-vocabulary.netlify.app/?path=/docs/hello-overview--page): 

> The overall Vocabulary project consists of:

	- Design Library (Figma), the source of truth for all designs in Vocabulary
	- Fonts (Typefaces), which provides typefaces and the main icon font for use in the system
	- Vocabulary (CSS library and assets), which provides base CSS styles for all components.
	- Vue Vocabulary (Vue.js library), which provides Vue components derived from Vocabulary

A design system that's primarily used within code, needs its `source of truth` to be actual code, and more specifically the `meaning` and `presentation`, and often `behavior` of various design elements. A program like Figma can somewhat provide the presentation part of the source of truth, but as it is more visually focused it is unreliable for the actual code (CSS) implementation of that presentation, and even less so for the meaning, which is mostly derived from the HTML markup. As for behavior, the results can largely be mixed from relying on Figma. This means resting the source of truth on Figma results in the presentation being incomplete, the behavior being inconsistent, and the meaning having to be derived elsewhere.

As a result, coming from an app-centric focus, the Vue.js Components and Vocabulary Styles ended up being closer to the actual original "source of truth" for meaning + some behavior + presentation, and this meant that Vue and by proxy Node conventions set the tone and direction of how and where Vocabulary could/should be used. This likely made solid sense considering the original focus and the original use of Vue.js in a larger application-centric approach. 

This doesn't make as much stable sense in the present, where WordPress themes largely need a CSS file of appropriate styles, and a directed documented implementation guide for how the markup should be output. The most direct implementation being as Gutenberg blocks on the b/e and as PHP code for the f/e rendering

There is also the possibility of the WordPress theme utilizing Vue.js Components into the mix, which paired with the backend editor (Gutenberg) being in React.js may introduce unnecessary complexity. 

The Vue.js components have a use, but they should be an implementation of `a source of truth` not the original `source of truth`. The current configuration leans too heavily on the latter.

#### Change in scale

At greater scale (multiple apps, higher number of engineers + teams) high reliability on a f/e framework (Vue.js, React.js, etc.) as the majority source of truth for components can be worth any complexities or missing pillars that come along because they help to not just enforce a Component, but to enforce that component's markup in a more direct, but also abstract pathway.

When the scale is not quite as large, these tradeoffs can come at a much higher cost. Additionally, if in the future there is a need to pivot away from utilizing a specific framework as the source of truth, then the migration path can be challenging since there is no framework agnostic source of truth to go back to as reference.

In general, if the project isn't going to have the kind of scale of a larger SAAS/PAAS company, it can make more sense for a Design System to first exist as a singular source of truth of components in as native of a format as possible (HTML, CSS, helper JS). There is some documentation of this within `storybook`, but it is inconsistent, some of the markup relying only on Vue markup.

Then, you can have various implementations in frameworks as they become relevant (Vue.js, React.js, etc.). This provides a stable source of truth that will remain relevant regardless of needed implementation. Changes to core Vocabulary can then cascade down to the individualistic implementations with their own specific nuances.

There are many sound reasons to pick one approach over another, or to pursue additional routes. However, much has changed since the original creation of Vocabulary, most importantly its use requirements, which include its scale. This has resulted in a high degree of complexity and code rot, which stands in the way of stable maintainability and accurate documentation.

### Incomplete Documentation

- The CI/CD pipeline and release process isn't documented in a cohesive location or format.
- How or where Vocabulary is used in various codebases isn't thoroughly documented, some repositories having overlapping versions

### Setup

* `creativecommons/vocabulary`
	- [ ] draft Issue outlining roadmap of changes / 2022.Q4 - 2023.Q1 Roadmap
	- [ ] paragraph for each phase breakout
	- [ ] adjacent repo specific issues needed?
- [ ] tag save points: `vocabulary-2020-2021-hybrid`
 	- core repositories:
		- [ ] `creativecommons/vocabulary`
		- [ ] `creativecommons/cc-assets`				
		- [ ] `creativecommons/vocabulary-components`		
		- [ ] `creativecommons/vocabulary-fonts`			
		- [ ] `creativecommons/vocabulary-styles`
	- downstream repositories?:
		- [ ] `creativecommons/creativecommons-certificate`		
		- [ ] `creativecommons/wp-theme-openglam`			
		- [ ] `creativecommons/creativecommons.github.io-source`	
		- [ ] `creativecommons/wp-theme-summit`			
		- [ ] `creativecommons/cc-global-components`			
		- [ ] `creativecommons/cc-legal-tools-data`			
		- [ ] `creativecommons/cc-legal-tools-app`			
		- [ ] `creativecommons/creativecommons-base`		
		- [ ] `creativecommons/chooser`

### Phase 1 <a id="phase-1"></a> 

Involves the `creativecommons/vocabulary` repository once again becoming the central hub of work, after several repositories have been combined, their functionality and associated NPM packages will be updated to reflect those changes, followed by changes with any projects which utilize those repositories as a dependency in some way.

- [ ] put notices at top of all main repos:
	- [ ] `creativecommons/vocabulary`
	- [ ] `creativecommons/cc-assets`				
	- [ ] `creativecommons/vocabulary-components`	
	- [ ] `creativecommons/vocabulary-fonts`			
	- [ ] `creativecommons/vocabulary-styles`
- [ ] `creativecommons/vocabulary` --> [remains, with new change branches as necessary]
- [ ] `creativecommons/vocabulary-components` --> `creativecommons/vocabulary-vue`
	- [ ] `unpkg/@creativecommons/vocabulary-components` --> `unpkg/@creativecommons/vocabulary-vue`
	- [ ] relink:
		- [ ] `creativecommons/chooser`
		- [ ] JS imports updated
- [ ] `creativecommons/cc-assets` --> `creativecommons/vocabulary-styles`
	- [ ] `unpkg/@creativecommons/cc-assets` --> `unpkg/@creativecommons/vocabulary-styles`
	- [ ] relink:
		- [ ] `creativecommons/chooser`
		- [ ] JS imports updated
	- [ ] archive repo
- [ ] `creativecommons/vocabulary-fonts` --> `creativecommons/vocabulary-styles`
	- [ ] `unpkg/@creativecommons/vocabulary-fonts`	--> `unpkg/@creativecommons/`vocabulary-styles
	- [ ] relink:
		- [ ] `creativecommons/creativecommons-base`
		- [ ] `creativecommons/cc-legal-tools-app`
		- [ ] `creativecommons/cc-legal-tools-data`
		- [ ] `creativecommons/cc-global-components`
		- [ ] includes updated
	- [ ] archive repo
- [ ] `creativecommons/vocabulary-styles` --> `creativecommons/vocabulary`
	- [ ] `unpkg/@creativecommons/vocabulary-styles` --> `unpkg/@creativecommons/vocabulary`
	- [ ] relink:
		- [ ] `creativecommons/creativecommons-base`
		- [ ] `creativecommons/cc-legal-tools-app`
		- [ ] `creativecommons/cc-legal-tools-data`
		- [ ] `creativecommons/cc-global-components`
		- [ ] includes updated
	- [ ] archive repo
- [ ] `creativecommons/vocabulary`
	- [ ] upgrade: 
		- [ ] `creativecommons/creativecommons-certificate`
		- [ ] `creativecommons/wp-theme-openglam`
		- [ ] `creativecommons/creativecommons.github.io-source`
		- [ ] `creativecommons/wp-theme-summit`
		- [ ] `creativecommons/cc-global-components`
	- [ ] `/packages/fonts` --> [remove]
		- [ ] `unpkg/@creativecommons/fonts` --> `unpkg/@creativecommons/vocabulary`
	- [ ] `/packages/vue-vocabulary` --> [remove]
		- [ ] `unpkg/@creativecommons/vue-vocabulary` --> `unpkg/@creativecommons/vocabulary-vue`
	
- [ ] `creativecommons/vocabulary`
	- [ ] `/packages/vocabulary` --> [move ..]
- [ ] new-setup:
	- [ ] `creativecommons/vocabulary` --> `@creativecommons/vocabulary`
	- [ ] `creativecommons/vocabulary-vue` --> `@creativecommons/vocabulary-vue`

### Phase 2 CDN Reconsideration

Vocabulary should not rely on being primarily a node package published to and served via npm/unpkg. This can remain secondarily, especially for node ecosystem specific projects, but for any other use cases that just need a `<link>` reference to utilize vocabulary there are better approaches, namely a simplistic CDN deployment pipeline that is not unpkg. 

- [ ] explore alternatives to unkpg
- [ ] establish baseline requirements (versioning, serving location scale, etc.)
- [ ] unpkg/@creativecommons/vocabulary			
	- `vocabulary.css` --> [custom cdn]
	- `vocabulary.js` --> [custom cdn]
					
### Phase 3 - Refactor Vocabulary to be proper source of truth

Much of the work thus far has mostly been to get the repositories reduced, clarify the code, and  make the CDN setup more robust. However, Vocabulary itself still needs the bulk of its code to be refactored. There is a strong likelihood that bulma needs to be removed/replaced, and that storybook needs a reconsideration.

- [ ] `creativecommons/vocabulary` --> [refactor transforms as proper design system hub, remove bulma]
- [ ] `creativecommons/vocabulary` --> [refactor builds css + js files] --> outputs to non unpkg CDN
- [ ] `creativecommons/vocabulary-vue` --> [refactor with vocabulary dependency, matching new spec}
- [ ] `creativecommons/vocabulary` --> [rewrite Storybook (or equivalent) to be new system explorer]

### Future Considerations
- [ ] `creativecommons/vocabulary-web-components` --> [new repo?]
- [ ] `creativecommons/vocabulary-react` --> [new repo?]
- [ ] `creativecommons/vocabulary`
	- `vocabulary-web-components.js` --> [custom cdn?]

**Comment by possumbilities** [comment]
These two items: 

- Ensure each repositories above has an admin team (probably "Internal Tech")
- Ensure each repositories above has an staff team in `.github/CODEOWNERS` (probably `@creativecommons/internal-tech`)

From: [[Request]: Push access to various Vocabulary related repositories for Sara Lovell #941](https://github.com/creativecommons/tech-support/issues/941#issuecomment-1251513923)

Need to be incorporated into the above Issue where relevant.
