### ISSUE TITLE
Consolidate and Implement Vocabulary across ancillary websites

### ISSUE THREAD

**Issue by Queen-codes** [creativecommons/vocabulary#329]
This is to document all of the tasks that'll be carried out during the Outreachy Dec 2024 cohort. 

Note: It's a work in progress and subject to change.

# Open Source website
- [creativecommons/creativecommons.github.io-source](https://github.com/creativecommons/creativecommons.github.io-source/): _Source files for CC Open Source website_

The work was done in two phases;

Phase 1: Refactoring to Vocabulary Markup: This phase focused on aligning the HTML structure with the Vocabulary markup for matching contexts . 
Phase 2:

### Global Header 

Before the start of the Outreachy program, efforts were made in the `vocab-refresh` branch to align the website's header with the global header component. During the program, the dropdown menu was removed from the header. However, there are plans to introduce dropdown functionality to Vocabulary in the future, so the dropdown menu might be reintroduced later.

This change was part of a larger pr to refactor the home page of the website;

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/856

### Global Footer

The footer menu was updated to align with the current menu structure, and the Twitter logo was replaced with Bluesky. These changes were made as part of a larger pull request:

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/856

However, during the refactoring phase, it was decided to include the menu from the legacy footer to provide a link to the archives page.

This adjustment was done in this commit: [include old menu back into footer](https://github.com/creativecommons/creativecommons.github.io-source/pull/880/commits/4dd7931dccd401f9dd14755e6e9e627762bf8766)  as part of 

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/880

### Recent Blog Posts
The recent blog was refactored to match vocab's context for blog index in pr;
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/851

### Homepage

Many changes were made to the homepage, which includes several sections: the Hero section, Get Involved section, Recent Blog Posts, and Featured Projects. During the refactoring phase, all legacy classes were removed. It was also decided to refactor the Get Involved section and Featured Projects to match the [ongoing initiative section](https://vocabulary-docs.netlify.app/specimen/contexts/program-index.html). 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/855
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/856

During the restyling of the homepage, a pull request was made:
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/888

In this PR, the plugin section from the Get Involved section was removed, as there are plans to archive this page. This change is reflected in the [remove our plugin commit](https://github.com/creativecommons/creativecommons.github.io-source/pull/888/commits/bd25520a7da2424b9bce75471c5c421c3d72a63b)

The Recent Blog Posts section, which resembled the Latest News section on the CC homepage, was restyled in the  [restyled recent blog post and changed order commit](https://github.com/creativecommons/creativecommons.github.io-source/pull/888/commits/3f8241ebf8c27d736f5af71ff4360f50364979ae). Additionally, the Get Involved and Featured Projects sections were adjusted to display in grids of 2 instead of 3. The call to action in the hero section was also decided to remain links instead of the button in the legacy design as they were better suited as links.

### Contribution, Work Program, Community Pages
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/858
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/859
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/861

Most of the pages and subsections under these categories were updated by refactoring the `page-with-toc.html` file in the codebase to align with the Vocabulary context. 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/862

### Community Team Page
as one of the pages not affected in the change made to the community page above, a pr was made to make changes to this page

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/863

In one of the previous discussions, there was a decision on how to handle instances where Vocabulary markup was not present for some of legacy code or vice-versa. This is explained in [comment](https://github.com/creativecommons/creativecommons.github.io-source/pull/854#issuecomment-2551705662).   As a result, the old table HTML markup was commented out and later reintroduced, as it was determined that presenting the data in a table format was the best approach, with all legacy classes stripped out.

Earlier efforts to align the team page with Vocabulary’s team markup faced an issue where placeholder images were used for team members instead of actual images. This led to the creation of the following issue:

- [ ] https://github.com/creativecommons/creativecommons.github.io-source/issues/869   - which is now blocked 

One of the localizations made was the decision to use [Datatables](https://datatables.net/) for styling the tables on the website. This change was included in this PR;
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/898

### Project list page 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/867
In this PR, the featured projects was made to align with the same on the home page, and the active project was maintained in a table format. 

The page was restyled in efforts made by this PR;
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/901

### Issue Finder Page
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/868
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/891
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/915

Related issue and PR to this
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/864
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/887
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/908
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/911
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/920

### Project idea page

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/871
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/910  

### Blog Page
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/860

This refactored the blog page to match the vocab-context for blog in this pr, this also involved making changes to the pagination
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/866

Another pr made in regards the issue above, for refactoring the page for each author to align with vocab's markup for person
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/865
It was in this pr, as stated in this [comment](https://github.com/creativecommons/creativecommons.github.io-source/pull/865#issuecomment-2565588773) that the route to dynamically add classes provided by vocabulary to reflect the page's styles was decided. 

To refactor the page that displays all authors;
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/870

 A pr was made to add the `blog-index` class for the blog post styles. Also,  in this pr, [pagination current display](https://github.com/creativecommons/creativecommons.github.io-source/pull/873/commits/31844a7b27bdf94c665bc23e1004aa5e2753352a) was fixed
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/873 

After the refactoring and due to the removal of legacy styles from the websites, some elements were not rendering properly, this was addressed in the issue and pr below,

- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/892

- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/903

An issue was raised to reduce the author picture size in the blog; 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/918
and a  pr was created 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/pull/927

#### Todo 
- [ ] Localize breadcrumb and secondary menu dropdowns

# Legal Database (Legal DB)
- [creativecommons/legaldb](https://github.com/creativecommons/legaldb): _CC Legal Database: curated repository of Case Law and Scholarship data from around the world in a Django based website._

Todo: decide on design Implenemtation strategies for-
- [ ] FAQ ? to be a localized feature or implemented upstream in vocabulary
- [ ] Search input on FAQ Page, Cases and Scholarship
- [ ] Color scheme on page: Cases currently use a red colour that can be updated to Vocabulary brand color tomato. For scholarship: Vocab color green or vocab dark green.
- [ ] Submission Page

#### Todo Open Issues -
- [x] https://github.com/creativecommons/legaldb/issues/280
- [x] https://github.com/creativecommons/legaldb/issues/279
- [x] https://github.com/creativecommons/legaldb/issues/278
- [x] https://github.com/creativecommons/legaldb/issues/277
- [x] https://github.com/creativecommons/legaldb/issues/281

# Search Portal
- [creativecommons/search](https://github.com/creativecommons/search): _Creative Commons Search Portal_
List of Issues Opened during the Outreachy Period
- [x] https://github.com/creativecommons/search/issues/321
- [x] https://github.com/creativecommons/search/issues/322
- [x] https://github.com/creativecommons/search/issues/325
- [x] https://github.com/creativecommons/search/issues/326
- [x] https://github.com/creativecommons/search/issues/329
- [x] https://github.com/creativecommons/search/issues/331
- [x] https://github.com/creativecommons/search/issues/333

PRs Opened 
- [x] https://github.com/creativecommons/search/pull/323
- [x] https://github.com/creativecommons/search/pull/324
- [x] https://github.com/creativecommons/search/pull/330

The PRs below were to update the search portal with the latest vocabulary version
- [x] https://github.com/creativecommons/search/pull/327 - this pr to remove the global summit was as a result of work done in vocabulary in this pr: https://github.com/creativecommons/vocabulary/issues/332

an update to the vocabulary was made twice, listed below
- [x] https://github.com/creativecommons/search/pull/332
- [x] https://github.com/creativecommons/search/pull/334 - an update to reflect efforts made in https://github.com/creativecommons/vocabulary/issues/335 and https://github.com/creativecommons/vocabulary/issues/337

a pr to unify the 404 pages across all ancillary websites was made, as a similar effort was done here: 
- [x] https://github.com/creativecommons/creativecommons.github.io-source/issues/877
- [x] https://github.com/creativecommons/search/pull/328

# Resource Archive 
- [creativecommons/cc-resource-archive](https://github.com/creativecommons/cc-resource-archive): _Collection of resources on Creative Commons (CC) tools and other open topics_

Issues opened during the outreach period

- [x] https://github.com/creativecommons/cc-resource-archive/issues/361
- [x] https://github.com/creativecommons/cc-resource-archive/issues/362
- [x] https://github.com/creativecommons/cc-resource-archive/issues/363
- [x] https://github.com/creativecommons/cc-resource-archive/issues/367
- [ ] https://github.com/creativecommons/cc-resource-archive/issues/359

PRs

- [x] https://github.com/creativecommons/cc-resource-archive/pull/364
- [x] https://github.com/creativecommons/cc-resource-archive/pull/365
- [x] https://github.com/creativecommons/cc-resource-archive/pull/366
- [x] https://github.com/creativecommons/cc-resource-archive/pull/368
- [ ] https://github.com/creativecommons/cc-resource-archive/pull/369
